### PR TITLE
Implement basic navigation.

### PR DESCRIPTION
**Pull request by godfath3r**
Implement basic navigation in repo.

### CODE REVIEW

**Comment by karate** [comment]
Once again I get `Not under version control.` when trying to enter a directory.

**Comment by karate** [comment]
Another thing. I just realized that navigation doesn't make much sense when viewing local status, because we show all dirs/files of interest.

**Comment by godfath3r** [comment]
Fixed.

**Comment by karate** [comment]
Thank you for your time!

Some issues I've find:

- Working copy doesn't need navigation. Hide the `l/h: in/out` status as well.
- Replace `l/h: in/out` with something more user-frienly, like `l: enter directory, h: previous directory`, and only when this makes sense (eg: do not show `h: previous directory` when `_nav_path` is empty)
- On remote browsing, all the screen is filled with empty lines. If the current directory has only a few files they are shown at the bottom, but the cursor is placed at the very first line of the screen, and I have to scroll all the way down through empty lines. Is there a way to clear the whole screen when the directory changes, instead of clearing each line?
- On remote browsing, hitting `l` on a file (instead of a directory) lists only that file, as if there is a folder with only that file in it. This is misleading. We should disable the `l` on non-folder entries.

**Comment by godfath3r** [comment]
Second point is not resolved. Need to find how ncurses work, but it looks like it behaves slightly different on each cmd line I've used.

**Comment by karate** [comment]
I guess you're referring to the 3rd point.
I managed to make it work by clearing the screen every time `browse_repo()` is called, and removed the code that fills the screen with empty lines. Since you've make such a nice work, please commit the following and I'll merge the PR.

```
diff --git a/filter.py b/filter.py
index 41f9cc5..28c111c 100644
--- a/filter.py
+++ b/filter.py
@@ -30,10 +30,6 @@ class Filter():
         for idx, f in enumerate(files):
             line = self.construct_line(f['path'], f['status'], idx+1)
             lines.append(line)
-        mlines, _ = self.screen.getmaxyx()
-        for i in range(len(files), mlines):
-            line = self.construct_line(' ', 'remote', i+1)
-            lines.append(line)
         return lines
 
     def construct_line( self, filename, status, idx ):
diff --git a/main.py b/main.py
index f0afc99..de1f804 100755
--- a/main.py
+++ b/main.py
@@ -123,6 +123,7 @@ class Navigation(object):
         self.input_nav()
 
     def browse_repo(self, rel=None):
+        self.c.screen.clear()
         self.base_status("browse loading...", text_only=True)
         d = dir.Dir(self._client)
         files = d.ls(rel)
```

**Comment by karate** [comment]
Closes #11

**Pull request merged**
