### PR TITLE
Use svn which is cross platform. Add requirements.txt.

### PR DESCRIPTION
**Pull request by godfath3r**
Changes made for working on windows. Please validate it still works on linux :D

### CODE REVIEW

**Comment by karate** [comment]
Thanks for the PR.

Remote repository browsing works.
Local status does not.

`client.list()` returns an array of strings (filenames) and our `filter_local_files` method won't work.
I tried `files = client.list(extended=True)`, but the returned dictionaries don't have a `status` key.

https://github.com/dsoprea/PySvn#listextendedfalse-rel_pathnone

I guess with the `svn` module, we will have to query every file, which is not ideal.

**Comment by godfath3r** [comment]
Working copy was given twice, one in object initialization and one on status.
Fixed now. 
It should be working.

**Comment by karate** [comment]
I was passing `working_copy` because in an earlier version (which didn't make it to github) you were able to enter and leave directories. Anyway, it's useless now. If this was a separate pull request, I'd merge

**Comment by godfath3r** [comment]
The last commit is part of this PR, that was the reason that it didn't work as it should.
I've tested svn python library and it works as it should both on windows and linux.

**Comment by karate** [comment]
Thank you. It works as expected!

**Pull request merged**
