### PR TITLE
Added keyring support

### PR DESCRIPTION
**Pull request by synackray**
I updated the login_handler function to leverage keyring. I also updated the .gitignore and requirements.txt to support virtual environments (venv).

### CODE REVIEW

**Comment by karate** [comment]
Thanks for the PR @synackray 

I see a lot of dependencies in `requirements.txt`. Are all these necessary?

Also, the `.gitignore` file is unnecessary long.
We should just mention files that our current setup may generate. You've even commited lines for Django and Flask.

Please make a more clean commit.
Also, make sure the imports in `main.py` are necessary.

**Comment by karate** [comment]
Another thing is that, with your implementation the svn user is hardcoded. That means that you can't have different users for different repos. Why not ask for the username along with the password?

**Comment by synackray** [comment]
> Another thing is that, with your implementation the svn user is hardcoded. That means that you can't have different users for different repos. Why not ask for the username along with the password?

Hello, @karate!

The code merged for credential management has the following workflow:
1. The user is prompted for their username. This is then set as the `USERNAME` variable for the keyring entry. 
[optional] A `USERNAME` variable is offered at the top of the script in-case the user has a common credential and does not wish to be prompted to enter their username on every call of the `login_handler` function.
2. The  `HOST` variable of the keyring entry is statically set to "svn_curse" (the program name). The user is prompted for their password **if** an existing credential is not already located in their keyring. Future queries for the username will match an existing keyring entry and the user will no longer be prompted for their password.

Based on your response, it makes sense to remove the static `HOST` variable and instead use the SVN URL collected from argv. This will adjust the workflow so that the keyring entries will always be associated to the SVN URL + URL specific username. Optionally, I can also remove the static `USERNAME` variable if it serves no value.

Please let me know if you agree and I'll adjust accordingly. Thanks!

**Comment by karate** [comment]
Thank you for the explanation. The workflow is fine as it is.
Also, let's keep the `USERNAME` variable.

As for the keyring `HOST` variable, I guess that the svn url will suffice. Is it possible to have different credentials on the same svn server, depending on the directory?

**Comment by synackray** [comment]
> I see a lot of dependencies in `requirements.txt`. Are all these necessary?

I did a quick parse and verified they are all dependencies of actively used packages in the program. I will do a manual review as well to make sure it's not a mistake. The main package adding dependencies is `keyring`.

> Also, the `.gitignore` file is unnecessary long.
> We should just mention files that our current setup may generate. You've even commited lines for Django and Flask.

The `.gitignore` included was pulled from Github's [gitignore repo](https://github.com/github/gitignore/blob/master/Python.gitignore). If you have preference, I can separate the `.gitignore` from the `login_handler` modifications PR. A more terse version can be generated to account for Python cache, virtualenv, and project-specific. 

> Please make a more clean commit.
> Also, make sure the imports in `main.py` are necessary.

This has been checked and validated in #6. I'll clean up the PRs and get back to you after. Thanks for all the help.

**Comment by synackray** [comment]
> Thank you for the explanation. The workflow is fine as it is.
> Also, let's keep the `USERNAME` variable.
> 
> As for the keyring `HOST` variable, I guess that the svn url will suffice. Is it possible to have different credentials on the same svn server, depending on the directory?

Yes I recommend taking the output of `_get_working_copy` function. Here is an example of the keyring entries using that method. This method ensures the same host can be used with different usernames as well. 

```
keyring.set_password("https://github.com/karate/svn_curse.git", "user1")
keyring.set_password("https://github.com/karate/svn_curse.git", "user2")
keyring.set_password("/home/user/Projects/svn_curse", "user1")
```

**Comment by synackray** [comment]
Cleaning up this PR by closing it out. Thanks so much for the opportunity, and best wishes!

**Pull request closed without merging**
