### PR TITLE
add exception

### PR DESCRIPTION
**Pull request by adrianocanofre**
I imagine this is a start to handling mistakes.

This PR is to #1 and to be able to start issue #8

### CODE REVIEW

**Comment by karate** [comment]
Thank you for the PR.

I get the following error:
```
Traceback (most recent call last):
  File "./main.py", line 5, in <module>
    import curse
  File "/home/karate/svn-curse/curse.py", line 34
    except curses.error as e
                           ^
SyntaxError: invalid syntax
```
Shouldn't this be `except curses.error as e:` (with a trailing colon)?

I'm using python 3.7.4

**Comment by adrianocanofre** [comment]
Yes, I adjusted it already

**Comment by karate** [comment]
There is a missing colon error in all exceptions that you wrote.

Please make sure that the PR doesn't break anything

**Comment by adrianocanofre** [comment]
Ok

**Comment by karate** [comment]
This doesn't work either.
Please try to run the program at least once, to make sure your changes work before submitting?

**Pull request closed without merging**
